[binarize]
enabled = true # Default: true
exclude = [
    "data/*.p3d",
    "data/anim/chop.rtm",
]

[rapify]
enabled = true # Default: true
exclude = [
    "missions/**/description.ext",
]

[files]
include = [
    "addons/*",
    "mod.cpp",        # These files are copied to the build directory by default
    "meta.cpp",       # They do not need to be added to your list
    "config.cpp",
    "LICENSE",
    "logo_ca.paa",
    "logoSmall_CA.paa",
    "logo_co.paa",
]

exclude = [
    ".vscode/**/*", # Exclude all files in the .vscode folder
    "data/*.psd",
    "media/*",
]